### PR TITLE
python3 compatibility

### PR DESCRIPTION
**Pull request by nlhepler**
use the six package for various conversions, remove python2 specific "-isms".

### CODE REVIEW

**Comment by jimporter** [comment]
Oh, whoops, I think I bitrotted this pretty badly by fixing all the linter issues in bfg. If you want, I can fix the bitrot, make any other changes I'd need for this, and land it.

**Comment by nlhepler** [comment]
@jimporter, no worries! I still need to address your comments, and then I'll rebase. =)

**Comment by nlhepler** [comment]
I dropped the darwin patch, we can address that later, hopefully by supporting @rpath and @install_name on OS X.

**Comment by nlhepler** [comment]
@jimporter, this should be good to go at this point. It only fails 8 tests on my local machine (OS X), all of them rpath-related.

**Comment by nlhepler** [comment]
Should fix #36, especially once we land CI support and enable version 3.4+ testing.

**Comment by nlhepler** [comment]
Thanks for the linter! I updated this commit to get rid of the warnings.

**Comment by jimporter** [comment]
Oh yeah, you may have already found this out, but I hooked up the linter so that it runs when you call `python setup.py lint`, assuming you have `flake8` already installed. That fixes some bugs flake8 has with its default setup.py hook.

**Comment by nlhepler** [comment]
That's what I used! I also hooked it up to TravisCI, so we can get linter and test compliance from PRs and so on! Ahh, the beautiful automation.

**Comment by jimporter** [comment]
Everything looks good! Time to merge!

**Comment by jimporter** [comment]
Ah, nuts. This breaks Python 2 since you can't use `exec` in a function with a nested function. I will fix that.

**Comment by nlhepler** [comment]
@jimporter, with what version? I've been using this on py2 and py3 back and forth w/o issue.

**Comment by jimporter** [comment]
Python 2.7.6. Also, I found another bug that happens only on Linux and predates this patch, but seems to have been revealed by me running in Python 3.4.3.

**Comment by nlhepler** [comment]
Weird that I don't get that error here. Well the solution is simple: move path_var out of main, or provide an empty dict as the third element of the tuple.

**Comment by jimporter** [comment]
Yeah, I just made a separate function. There are a couple of other things I noticed that are Linux- and Windows-specific that need fixing too. Also, I guess I'll have to figure out if I can come up with an easy way to use relative imports in the integration tests that still let me run a single test file (or maybe I can just do that via setup.py...).

**Comment by jimporter** [comment]
Ok, I landed the followup fixes, and I can just use `python setup.py test -s <module>` to run a single file. :D

**Comment by nlhepler** [comment]
It might be cleaner to do the dict(), actually, as it will prevent the user's bfgfile from dumping variables into the driver.

Yea, I struggled with the relative import thing as well, because I saw all those main functions, and guessed that's what you used them for..

**Comment by nlhepler** [comment]
There's also `python -m unittest test.integration.test_env_vars`

**Comment by jimporter** [comment]
> It might be cleaner to do the dict(), actually, as it will prevent the user's bfgfile from dumping variables into the driver.

Makes sense.

I'll probably remove all the main functions from the tests as they're obsolete now (and not really worth futzing with Python's import statements to make it work).

**Pull request merged**
